server:
  port: 9000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tavern?serverTimezone=GMT%2B8
    username: dev
    password: dev123
    driver-class-name:

logging:
  level:
    com.cyberparadise.world.tavern.dao.mybatis: debug
